python pacman.py -l test1.lay -q
python pacman.py -l test2.lay -q
python pacman.py -l test3.lay -q
python pacman.py -l test4.lay -q
python pacman.py -l test5.lay -q
python pacman.py -l test6.lay -q
python pacman.py -l test7.lay -q
python pacman.py -l test8.lay -q
python pacman.py -l test9.lay -q
python pacman.py -l test10.lay -q
python pacman.py -l test11.lay -q
python pacman.py -l test12.lay -q
python pacman.py -l test13.lay -q
python pacman.py -l test14.lay -q
python pacman.py -l test15.lay -q
python pacman.py -l test16.lay -q
python pacman.py -l test17.lay -q
python pacman.py -l test18.lay -q
python pacman.py -l test19.lay -q
python pacman.py -l test20.lay -q
python pacman.py -l test21.lay -q
python pacman.py -l test22.lay -q
python pacman.py -l test23.lay -q
python pacman.py -l test24.lay -q
python pacman.py -l test25.lay -q
python pacman.py -l test26.lay -q
python pacman.py -l test27.lay -q
python pacman.py -l test28.lay -q
python pacman.py -l test29.lay -q
python pacman.py -l test30.lay -q
python pacman.py -l test31.lay -q
python pacman.py -l test32.lay -q
python pacman.py -l test33.lay -q
python pacman.py -l test34.lay -q
python pacman.py -l test35.lay -q
python pacman.py -l test36.lay -q
python pacman.py -l test37.lay -q
python pacman.py -l test38.lay -q
python pacman.py -l test39.lay -q
python pacman.py -l test40.lay -q
python pacman.py -l test41.lay -q
python pacman.py -l test42.lay -q
python pacman.py -l test43.lay -q
python pacman.py -l test44.lay -q
python pacman.py -l test45.lay -q
python pacman.py -l test46.lay -q
python pacman.py -l test47.lay -q
python pacman.py -l test48.lay -q
python pacman.py -l test50.lay -q
python pacman.py -l test51.lay -q
python pacman.py -l test52.lay -q
python pacman.py -l test53.lay -q
python pacman.py -l test54.lay -q
python pacman.py -l test55.lay -q
python pacman.py -l test56.lay -q
python pacman.py -l test57.lay -q
python pacman.py -l test58.lay -q
python pacman.py -l test59.lay -q
python pacman.py -l test60.lay -q
python pacman.py -l test61.lay -q
python pacman.py -l test62.lay -q
python pacman.py -l test63.lay -q
python pacman.py -l test64.lay -q
python pacman.py -l test65.lay -q
python pacman.py -l test66.lay -q
python pacman.py -l test67.lay -q
python pacman.py -l test68.lay -q
python pacman.py -l test69.lay -q
python pacman.py -l test70.lay -q
python pacman.py -l test71.lay -q